name: Playwright JS Diploma /w UI and API tests
# Запускаем при пуше в main ветку:
on:
  push:
    branches:
      - main
  # Ручной запуск:
  workflow_dispatch:

jobs:
  All_UI_and_API_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
      - name: Установка npm пакеты из package.json
        run: npm ci
      - name: Установка браузеров
        run: npx playwright install --with-deps
      - name: Запускаем тесты
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: npm t
      - name: Сгенерировать Allure отчет в один файл
        run: npx allure awesome ./allure-results --single-file
        continue-on-error: true
        if: always()
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        continue-on-error: true
        if: always()
        with:
          name: Allure Report
          path: |
            allure-report/index.html
            allure-results
            playwright-report
